# Generated by Django 5.0.4 on 2024-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефонный номер'),
        ),
    ]
