# Generated by Django 5.0.4 on 2024-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
    ]
