# Generated by Django 5.0.4 on 2024-05-01 19:55

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_last_name_alter_contacts_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Сообщение')),
                ('title', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession', models.CharField(max_length=255, verbose_name='Ваша Профессия')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('descriptions', models.TextField(max_length=255, verbose_name='Описание про нащих услуг')),
            ],
            options={
                'verbose_name_plural': 'Услуга',
            },
        ),
    ]
