# Generated by Django 5.0.4 on 2024-05-04 13:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_review_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriptions',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Описание про нащих услуг'),
        ),
    ]
