# Generated by Django 5.0.4 on 2024-05-04 13:48

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legalinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name=' Первое Описание')),
                ('descriptions2', ckeditor.fields.RichTextField(verbose_name='Второе Описание')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_image/', verbose_name='Фотография')),
                ('image2', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_image/', verbose_name='2 Фотография')),
            ],
            options={
                'verbose_name_plural': 'Юридическая информация',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Название')),
                ('data', models.CharField(max_length=255, verbose_name='Дата')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name=' Первое Описание')),
                ('descriptions2', ckeditor.fields.RichTextField(verbose_name='Второе Описание')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_image/', verbose_name='Фотография')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ФИО')),
                ('work', models.CharField(max_length=255, verbose_name='Профессия')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='team_image/', verbose_name='Ваше фото')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
            ],
            options={
                'verbose_name': 'Наши юристы',
                'verbose_name_plural': 'Наш юрист',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history_images/', verbose_name='Фотография')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='secondary.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
