# Generated by Django 5.0.4 on 2024-04-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutInline',
        ),
    ]
