# Generated by Django 5.0.4 on 2024-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_delete_aboutinline'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decriptions', models.TextField(verbose_name='Первое описание')),
                ('decriptions2', models.TextField(verbose_name='Второе описание')),
                ('image', models.ImageField(upload_to='about_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
