# Generated by Django 5.0.4 on 2024-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=255, verbose_name='Год')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Наши истории',
                'verbose_name_plural': 'Наша история',
            },
        ),
    ]
