# Generated by Django 5.0.4 on 2024-04-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_category_alter_history_options_alter_year_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='category',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
