# Generated by Django 5.0.4 on 2024-04-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_remove_year_category_rename_year_year_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='title',
            new_name='years',
        ),
    ]
