# Generated by Django 5.0.4 on 2024-04-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_rename_title_year_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='years',
            new_name='title',
        ),
    ]
