# Generated by Django 5.0.4 on 2024-04-30 00:06

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_rename_years_year_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Первое описание')),
                ('descriptions2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Второе описание')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='descriptions3',
            field=models.TextField(default=1, verbose_name='Конец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions',
            field=models.TextField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions2',
            field=models.TextField(verbose_name='Середина'),
        ),
    ]
