# Generated by Django 5.0.4 on 2024-04-30 00:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_singleparts_news_descriptions3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleparts',
            options={'verbose_name_plural': 'Одиночные детали'},
        ),
        migrations.RemoveField(
            model_name='singleparts',
            name='descriptions2',
        ),
        migrations.AddField(
            model_name='singleparts',
            name='video',
            field=models.URLField(default=1, verbose_name='Видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleparts',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
