# Generated by Django 5.0.4 on 2024-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('image', models.ImageField(upload_to='client_image/', verbose_name='Ваше фото')),
                ('title', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession', models.CharField(max_length=255, verbose_name='Ваша апрфессия')),
            ],
            options={
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servie_image', verbose_name='Наши услуги')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание про нащих услуг')),
            ],
            options={
                'verbose_name_plural': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo_site')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('logate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
