# Generated by Django 5.0.4 on 2024-04-24 14:47

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_setting_descriptions_alter_setting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo_image/', verbose_name='Логотип')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('logate', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram url')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook url')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtube url')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp url')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
