# Generated by Django 5.0.4 on 2024-04-24 15:58

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_settings_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Ваше фото'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profession',
            field=models.CharField(max_length=255, verbose_name='Ваша Профессия'),
        ),
    ]
