# Generated by Django 5.0.4 on 2024-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
