# Generated by Django 5.0.4 on 2024-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_slide_settings_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото для сайта')),
                ('image1', models.ImageField(upload_to='image1/', verbose_name='2 Фото для сайта')),
            ],
            options={
                'verbose_name_plural': 'Слайд',
            },
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
    ]
