# Generated by Django 5.0.4 on 2024-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Довольные клиенты')),
                ('team', models.CharField(max_length=255, verbose_name='Опытные юристы и адвокаты')),
                ('experience', models.CharField(max_length=255, verbose_name='Многолетний опыт')),
                ('critical', models.CharField(max_length=255, verbose_name='Критические случаи успешно решены')),
                ('review', models.CharField(max_length=255, verbose_name='Положительных отзывов')),
            ],
            options={
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
