# Generated by Django 5.0.4 on 2024-04-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
