# Generated by Django 5.0.4 on 2024-04-26 10:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
