# Generated by Django 5.0.4 on 2024-04-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='logate',
            new_name='locate',
        ),
    ]
