# Generated by Django 5.0.4 on 2024-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_review_message_alter_settings_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriptions',
            field=models.TextField(max_length=255, verbose_name='Описание про нащих услуг'),
        ),
    ]
