# Generated by Django 5.0.4 on 2024-05-01 19:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_about_delete_injury_delete_legalinsights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptions2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Второе описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=models.TextField(verbose_name='Первое описание'),
        ),
    ]
